Uses cases Update
xmtp/xmtp-dot-org pull request #655
Opened 2024-02-13 19:46 UTC by fabriguespe

Uses cases update with groups and frames use cases

2024-02-13 21:43 UTC, scotboyd requested changes

2024-02-13 21:43 UTC, scotboyd commented on docs/use-cases/commerce.mdx
> +- **Order confirmations**:XMTP can be used to securely confirm orders, ensuring that both buyers and sellers have verifiable proof of purchase and sale without exposing sensitive information.
```suggestion
- **Order confirmations**: XMTP can be used to securely confirm orders, ensuring that both buyers and sellers have verifiable proof of purchase and sale without exposing sensitive information.
```

2024-02-13 21:43 UTC, scotboyd commented on docs/use-cases/commerce.mdx
> +- **Approval requests** : Whether it's for returns, custom orders, or any situation requiring explicit approval, XMTP facilitates these requests securely.
```suggestion
- **Approval requests**: Whether it's for returns, custom orders, or any situation requiring explicit approval, XMTP facilitates these requests securely.
```

2024-02-13 21:43 UTC, scotboyd commented on docs/use-cases/dao.mdx
> +- **Subscription to a user**:Enabling users to subscribe to specific members or activities within the DAO. This feature allows for targeted communication and keeps members engaged and informed about
```suggestion
- **Subscription to a user**: Enabling users to subscribe to specific members or activities within the DAO. This feature allows for targeted communication and keeps members engaged and informed about relevant updates.
```

2024-02-13 21:43 UTC, scotboyd commented on docs/use-cases/dao.mdx
> +- **Group chat between members** : Creating a secure and transparent platform for members to communicate with each other. Such a platform could be built with features to authenticate messages and par
```suggestion
- **Group chat between members**: Creating a secure and transparent platform for members to communicate with each other. Such a platform could be built with features to authenticate messages and participants, thus creating a more trustworthy environment.
```

2024-02-15 22:16 UTC, fabriguespe reviewed
Thanks for the changes!

2024-02-15 22:24 UTC, merged