Deprecate flutter
xmtp/xmtp-dot-org pull request #710
Opened 2024-04-05 18:50 UTC by fabriguespe

2024-04-08 16:35 UTC, fabriguespe commented
Hey @scotboyd ! What do you think if we just hide the tabs with CSS for now? IN case we need to get this back up in a month or two.

2024-04-08 16:38 UTC, scotboyd commented
I have no problem doing it that way if it works.

2024-04-08 16:44 UTC, scotboyd commented
I don't think we should rewrite the history of the change log, we should just remove the link and potentially put text that says "This has since been deprecated."

Also I notice that we haven't updated the change log since December.  Should we have updated it for the Denver releases?

2024-04-10 17:08 UTC, fabriguespe commented
You are right @scotboyd thank you. I just added back the changelog entries. Regarding the change log yes hasn't been updated this year. Lets start another PR. Sounds good.

2024-04-10 17:22 UTC, scotboyd requested changes
Took another look and noticed a spelling error.

2024-04-10 17:22 UTC, scotboyd commented on docs/faq.md
> +The XMTP SDK is [available for multiple languages](/docs/introduction#xmtp-sdks-and-example-apps#sdks), including JavaScript, Kotli and Swift.
```suggestion
The XMTP SDK is [available for multiple languages](/docs/introduction#xmtp-sdks-and-example-apps#sdks), including JavaScript, Kotlin and Swift.
```

2024-04-10 17:23 UTC, scotboyd approved these changes

2024-04-10 17:50 UTC, alexrisch approved these changes

2024-04-10 19:24 UTC, merged